export const storeProducts = [
  {
    id: 1,
    title: "IPhone 11",
    img: "../assets/phone.png",
    price: 3799,
    company: "Apple",
    mainCamera: 12,
    secondCamera: 12,
    storage: 128,
    ram: 4,
    diagonal: 6.1,
    description:
      "Nowy system dwóch aparatów pozwala uchwycić więcej. Najszybszy procesor w historii smartfonów i bateria na cały dzień – jeszcze więcej zdziałasz. A dzięki wideo o jakości nieosiągalnej dla żadnego innego smartfona zapisane wspomnienia będą wyglądać piękniej niż kiedykolwiek.",
  },
  {
    id: 2,
    title: "IPhone 12",
    img: "",
    price: 3799,
    company: "Apple",
    mainCamera: 12,
    secondCamera: 12,
    storage: 128,
    ram: 4,
    diagonal: 6.1,
    description:
      "Nowy system dwóch aparatów pozwala uchwycić więcej. Najszybszy procesor w historii smartfonów i bateria na cały dzień – jeszcze więcej zdziałasz. A dzięki wideo o jakości nieosiągalnej dla żadnego innego smartfona zapisane wspomnienia będą wyglądać piękniej niż kiedykolwiek.",
  },
  {
    id: 3,
    title: "IPhone 13",
    img: "",
    price: 3799,
    company: "Apple",
    mainCamera: 12,
    secondCamera: 12,
    storage: 128,
    ram: 4,
    diagonal: 6.1,
    description:
      "Nowy system dwóch aparatów pozwala uchwycić więcej. Najszybszy procesor w historii smartfonów i bateria na cały dzień – jeszcze więcej zdziałasz. A dzięki wideo o jakości nieosiągalnej dla żadnego innego smartfona zapisane wspomnienia będą wyglądać piękniej niż kiedykolwiek.",
  },
];

// export const storeProducts = {
//   'samsung': {
//     0: {
// 	    title: "Samsung Galaxy S20",
// 	    color: "Blue",
// 	    os: "Android 10",
//       price: 3500,
//       mainCamera: 64,
//       secondCamera: 10,
//       storage: 128,
//       ram: 8,
//       diagonal: 6.2,
// 	    battery: "4000",
//       description:
//         "Nowy system dwóch aparatów pozwala uchwycić więcej. Najszybszy procesor w historii smartfonów i bateria na cały dzień – jeszcze więcej zdziałasz. A dzięki wideo o jakości nieosiągalnej dla żadnego innego smartfona zapisane wspomnienia będą wyglądać piękniej niż kiedykolwiek.",
// 	  },
// 	  1: {
// 	    title: "Samsung Galaxy S10",
// 	    color: "Black",
// 	    os: "Android 9",
//       price: 3100,
//       mainCamera: 16,
//       secondCamera: 10,
//       storage: 128,
//       ram: 8,
//       diagonal: 6.1,
// 	    battery: "4000",
//       description:
//         "Samsung Galaxy S10 to flagowy smartfon koreańskiego producenta na 2019 rok. Wyróżnia się doskonałym wyświetlaczem Dynamic AMOLED o bardzo smukłych ramkach i wysokiej rozdzielczości 1440x3040 pikseli, a także dużą wydajnością zapewnianą przez procesor Exynos 9820 i 8 GB pamięci RAM.",
// 	  },
//     2: {
// 	    title: "Samsung Galaxy A20e",
// 	    color: "Black",
// 	    os: "Android 9",
//       price: 650,
//       mainCamera: 13,
//       secondCamera: 8,
//       storage: 32,
//       ram: 3,
//       diagonal: 5.8,
// 	    battery: "3000",
//       description:
//         "Galaxy A20e jest najbardziej kompaktowym smartfonem z serii A. Posiada wyświetlacz Infinity Display, zawierający proporcje ekranu do obudowy na poziomie przekraczającym 90%, zaawansowana funkcja wielu okien, Live Bokeh Effect. Obudowa urządzenia została wykonana z eleganckich materiałów, co zapewnia telefonowi unikalne wzornictwo oraz sprawia, że smartfon idealnie układa się w dłoni.",
// 	  },
//     3: {
// 	    title: "Samsung Galaxy A51",
// 	    color: "Blue",
// 	    os: "Android 10",
//       price: 1500,
//       mainCamera: 48,
//       secondCamera: 32,
//       storage: 128,
//       ram: 4,
//       diagonal: 6.5,
// 	    battery: "4000",
//       description:
//         "Smukła, praktycznie bezramkowa obudowa czarnego Samsung Galaxy A51, zachwyca szerokim ekranem Infinity O z matrycą Super AMOLED. Tył smartfonu zaskakuje holograficznym połyskiem oraz przyciągającym wzrok geometrycznym wzorem. Prawdziwą rewolucją są jednak cztery aparaty główne, otwierające przed tobą zupełnie nową jakość fotografii. Co więcej, mocne podzespoły, wytrzymała bateria oraz wsparcie sztucznej inteligencji sprawiają, że wszystko, co robisz na Galaxy A51 przebiega szybko i sprawnie.",
// 	  }
//   },
//   'xiaomi': {
//     0: {
// 	    title: "Xiaomi Mi 10",
// 	    color: "Grey",
// 	    os: "Android 10",
//       price: 3300,
//       mainCamera: 108,
//       secondCamera: 20,
//       storage: 128,
//       ram: 8,
//       diagonal: 6.67,
// 	    battery: "4780",
//       description:
//         "Najciekawsza premiera roku. Twórz niesamowite wideo aparatem 108MP z Xiaomi Mi 10. Olbrzymia bateria, super ostry ekran AMOLED, obsługa standardów 5G i najnowszy procesor Qualcomm Snapdragon.",
// 	  },
//     1: {
// 	    title: "Xiaomi Redmi Note 8 Pro",
// 	    color: "Green",
// 	    os: "Android 9",
//       price: 1000,
//       mainCamera: 64,
//       secondCamera: 20,
//       storage: 64,
//       ram: 4,
//       diagonal: 6.5,
// 	    battery: "4500",
//       description:
//         "Legendarny Redmi Note powraca w nowej, ósmej wersji! Redmi Note 8 Pro jako pierwszy w rodzinie Redmi wprowadza szybką, bezprzewodową łączność NFC. Profesjonalnej jakości aparat główny 64MP wspomagany dodatkowymi matrycami 8+2+2MP za każdym razem uchwyci doskonałe ujęcia, odpowiednio dopasowując scenerię przy pomocy SI. Redmi Note 8 Pro to także topowy procesor Helio G90T, pamięć 6GB RAM oraz olbrzymia bateria 4500mAh.",
// 	  },
//     2: {
// 	    title: "Xiaomi Redmi 6A",
// 	    color: "Gold",
// 	    os: "Android 8.1",
//       price: 455,
//       mainCamera: 64,
//       secondCamera: 13,
//       storage: 5,
//       ram: 2,
//       diagonal: 5.45,
// 	    battery: "3000",
//       description:
//         "Smukła, poręczna konstrukcja z którą nie zechcesz się rozstać. Redmi 6A został zaprojektowany tak, aby dać szerokie pole widzenia i wciąż wygodnie mieścić się w Twojej dłoni. Z 5,45'' ekranem HD w proporcji 18:9, zajmującym 80,5% powierzchni przedniej telefonu, doświadczasz kinowych wrażeń w smukłej ramce, która idealnie mieści się w Twojej dłoni.",
// 	  },
//     3: {
// 	    title: "Xiaomi Pocophone F1",
// 	    color: "Black",
// 	    os: "Android 8.1",
//       price: 1500,
//       mainCamera: 12,
//       secondCamera: 20,
//       storage: 64,
//       ram: 6,
//       diagonal: 6.18,
// 	    battery: "4000",
//       description:
//         "POCOPHONE F1 to prawdziwy demon szybkości. napędzany przez ośmiordzeniowy procesor Snapdragon 845 z płynnym systemem chłodzenia. Podwójna kamera tylna obsługuje automatyczny tryb auto-focus Dual Pixel, a pojemność baterii wynosi aż 4000 mAh, wspierana przez technologię szybkiego ładowania Quick Charge 3.0.",
// 	  }
//   },
//   'nokia': {
//     0: {
// 	    title: "Nokia 6.1",
// 	    color: "Black",
// 	    os: "Android 8.0",
//       price: 1200,
//       mainCamera: 16,
//       secondCamera: 8,
//       storage: 32,
//       ram: 3,
//       diagonal: 5.5,
// 	    battery: "3000",
//       description:
//         "Jednolitą konstrukcję granatowo-złotej Nokia 6.1 wyrzeźbiono z pojedynczego bloku aluminium, a następnie poddano procesowi anodowania. Front smartfonu to tafla szkła 2.5D chroniącego matrycę 5,5” Full HD. Wyświetlacz otaczają minimalistyczne, zaokrąglone na rogach ramki, których krawędzie podkreślono subtelną złotą linią. Motyw ten powtórzono również na pierścieniach otaczających czytnik linii papilarnych oraz obiektyw aparatu 16 Mpix. W rezultacie, Nokia 6.1 wyróżnia się unikalnym i eleganckim wyglądem.",
// 	  },
//     1: {
// 	    title: "Nokia 1.3",
// 	    color: "Black",
// 	    os: "Android 10",
//       price: 420,
//       mainCamera: 8,
//       secondCamera: 5,
//       storage: 16,
//       ram: 1,
//       diagonal: 5.71,
// 	    battery: "3000",
//       description:
//         "Smartfon Nokia 1.3 można scharakteryzować krótkim hasłem: znacznie więcej. Mieszczący dużo treści wyświetlacz HD+ o przekątnej 5,71 cala, funkcje fotograficzne umożliwiające robienie znakomitych zdjęć przy słabym oświetleniu oraz całodzienna bateria, która zapewnia energię na dłużej. Do tego system operacyjny Android 10 (wersja Go) pozwalający załatwiać sprawy szybciej i bezpieczniej.",
// 	  },
//     2: {
// 	    title: "Nokia Lumia 1020",
// 	    color: "Black",
// 	    os: "MS Windows Phone 8",
//       price: 1050,
//       mainCamera: 38,
//       secondCamera: 1.2,
//       storage: 32,
//       ram: 2,
//       diagonal: 4.5,
// 	    battery: "2000",
//       description:
//         "Nokia Lumia 1020 wyposażona w matrycę o rozdzielczości aż 41 megapikseli wyróżnia się nowym podejściem do przybliżania obrazu, dzięki czemu użytkownicy mogą zawrzeć na zdjęciach nawet szczegóły niezauważalne dla oka. Dzięki technologii PureView firmy Nokia z optyczną stabilizacją obrazu smartfon ten uzyskuje ostrości zdjęć jak najlepsze aparaty cyfrowe. Możliwości takie zapewnia połączenie wiodących rozwiązań sprzętowych z nową aplikacją Nokia Pro Camera, za pomocą której każdy może robić łatwo zdjęcia o profesjonalnej jakości. Nowa funkcja w smartfonie Nokia Lumia 1020 umożliwia jednoczesne robienie zdjęcia o wysokiej rozdzielczości 38 megapikseli do edycji bez ograniczeń oraz 5-megapikselowej wersji do udostępniania w serwisach społecznościowych za pośrednictwem systemu Windows Phone 8. Matrycy o rozdzielczości 41 megapikseli w smartfonie Nokia Lumia 1020 towarzyszy układ optyczny ZEISS z sześcioma obiektywami fizycznymi, a także funkcją optycznej stabilizacji obrazu.",
// 	  },
//     3: {
// 	    title: "Nokia 7.2",
// 	    color: "Black",
// 	    os: "Android 9",
//       price: 1400,
//       mainCamera: 48,
//       secondCamera: 20,
//       storage: 128,
//       ram: 6,
//       diagonal: 6.3,
// 	    battery: "3500",
//       description:
//         "Wytrzymała i lekka Nokia 7.2 64 GB czarna, wyróżnia się solidnym metalowym korpusem oraz smukłą poliwęglanową ramką, która harmonijnie łączy się z zaokrąglonym szkłem ekranu. Na gładkiej tylnej obudowie umieszczono pierścień mieszczący zestaw trzech obiektywów aparatu głównego. Dodatkowo, smartfon wyposażono w wydajne podzespoły z 8-rdzeniowym procesorem Snapdragon 660 oraz adaptacyjną baterią wytrzymującą nawet 2 dni bez ładowania. Całość uzupełnia wsparcie inteligentnego asystenta Google.",
// 	  }
//   },
//   'oneplus': {
//     0: {
// 	    title: "OnePlus 7 Pro",
// 	    color: "Grey",
// 	    os: "Android 9",
//       price: 3100,
//       mainCamera: 40,
//       secondCamera: 16,
//       storage: 256,
//       ram: 8,
//       diagonal: 6.7,
// 	    battery: "4000",
//       description:
//         "Poznaj smartfon, który wyznacza nowy poziom szybkości, jakości obrazu i perfekcji fotografii - oto OnePlus 7 Pro. Pierwszy powita Cię w nim panoramiczny ekran Fluid AMOLED o rozdzielczości QHD+. Zaraz potem porwie Cię wydajność flagowego procesora Snapdragon 855.",
// 	  },
//     1: {
// 	    title: "OnePlus 7T",
// 	    color: "Silver",
// 	    os: "Android 10",
//       price: 2600,
//       mainCamera: 48,
//       secondCamera: 16,
//       storage: 128,
//       ram: 8,
//       diagonal: 6.5,
// 	    battery: "3800",
//       description:
//         "OnePlus 7T został zaprojektowany, aby cieszyć – wydajnością, elegancją i trwałością. Wykonany z nowoczesnych i trwałych materiałów, wyposażony w 6,55-calowy ekran AMOLED, a przede wszystkim gotów do tego, by ująć Cię swoją bezkompromisowością. Oto OnePlus 7T – smartfon idealny zarówno do pracy, jak również do multimediów i fotografii. Smartfon w sam raz dla Ciebie.",
// 	  },
//     2: {
// 	    title: "OnePlus 6",
// 	    color: "White",
// 	    os: "Android 8.1",
//       price: 2700,
//       mainCamera: 20,
//       secondCamera: 1.2,
//       storage: 128,
//       ram: 8,
//       diagonal: 6.28,
// 	    battery: "3300",
//       description:
//         "Ekskluzywny design OnePlus 6 128 GB Mirror Black wyraża zamiłowanie do perfekcji. Precyzji wykonania, doskonałych osiągów, profesjonalnej jakości zdjęć. Dwie tafle twardego, a zarazem połyskliwego szkła spięto metalową klamrą, tworząc urzekająco smukłą sylwetkę. Piękna to bestia, wyposażona w podwójny aparat, ekran AMOLED 19:9 oraz potężny procesor Snapdragon 845 i 8 GB pamięci RAM. A baterię OnePlus 6 uzupełnisz błyskawicznie, by znów czerpać radość z niezwykłych możliwości smartfona.",
// 	  },
//     3: {
// 	    title: "OnePlus 8",
// 	    color: "Green",
// 	    os: "Android 10",
//       price: 3700,
//       mainCamera: 48,
//       secondCamera: 16,
//       storage: 256,
//       ram: 12,
//       diagonal: 6.5,
// 	    battery: "4300",
//       description:
//         "Potężna wydajność 5G Pobieraj filmy w kilka sekund, udostępniaj zdjęcia niemal natychmiast i uzyskaj pełny zasięg sieci dzięki 5G. Wzmocnij swój dzień i noc. Warp Charge 30T zabierze Cię od 1% do 50% w zaledwie 22 minuty. A dzięki dużej pojemności baterii 4300 mAh Twój telefon ma moc, której potrzebujesz do całodziennego użytkowania.",
// 	  }
//   },
//   'apple': {
//     0: {
// 	    title: "iPhone 11",
// 	    color: "Black",
// 	    os: "iOS 13",
//       price: 3800,
//       mainCamera: 12,
//       secondCamera: 12,
//       storage: 128,
//       ram: 4,
//       diagonal: 6.1,
// 	    battery: "3100",
//       description:
//         "Nowy system dwóch aparatów pozwala uchwycić więcej. Najszybszy czip w historii smartfonów i bateria na cały dzień – jeszcze więcej zdziałać. A dzięki wideo o jakości nieosiągalnej dla żadnego innego smartfona zapisane wspomnienia będą wyglądać piękniej niż kiedykolwiek.",
// 	  },
//     1: {
// 	    title: "iPhone 11 Pro",
// 	    color: "Silver",
// 	    os: "iOS 13",
//       price: 4900,
//       mainCamera: 12,
//       secondCamera: 12,
//       storage: 128,
//       ram: 8,
//       diagonal: 5.8,
// 	    battery: "3100",
//       description:
//         "Przełomowy system trzech aparatów, który daje nieporównanie więcej możliwości, w niczym nie komplikując obsługi. Bezprecedensowy skok wydajności baterii. Oraz czip o niesamowitej mocy, który zwielokrotnił zdolności samouczenia, radykalnie przesuwając granice tego, co potrafią smartfony. Ten iPhone w pełni zasługuje na swoje imię.",
// 	  },
//     2: {
// 	    title: "iPhone SE 2020",
// 	    color: "Red",
// 	    os: "iOS 13",
//       price: 2200,
//       mainCamera: 12,
//       secondCamera: 7,
//       storage: 64,
//       ram: 3,
//       diagonal: 4.7,
// 	    battery: "3100",
//       description:
//         " Poznaj Apple iPhone SE 2020  fenomen, który łączy w sobie najpotężniejszy procesor, najpopularniejszy rozmiar oraz najlepszą cenę. W pakiecie otrzymujesz wyjątkowy 4,7-calowy wyświetlacz Retina HD. Całość zamknięto w wytrzymałej obudowie wykonanej ze szkła i aluminium, a do tego jest wodoodporna. Nad błyskawiczną prędkością działania czuwa wybitny czip, który swą wydajnością zasłyną już w urządzeniach z serii 11 Pro. Nowy iPhone SE to również fenomenalne zdjęcia oraz niezwykle wytrzymała bateria.",
// 	  },
//     3: {
// 	    title: "iPhone 8",
// 	    color: "Silver",
// 	    os: "iOS 11",
//       price: 2200,
//       mainCamera: 12,
//       secondCamera: 7,
//       storage: 64,
//       ram: 2,
//       diagonal: 4.7,
// 	    battery: "1821",
//       description:
//         "iPhone 8 ma całkowicie nową szklaną obudowę. Udoskonalony najpopularniejszy aparat na świecie. Najpotężniejszy i najinteligentniejszy procesor w historii smartfonów. Ładowanie bezprzewodowe łatwe jak nigdy. I nowe, dotąd niemożliwe zastosowania rozszerzonej rzeczywistości. Oto iPhone nowej generacji.",
// 	  }
//   },
//   'huawei': {
//     0: {
// 	    title: "Huawei P30",
// 	    color: "Blue",
// 	    os: "Android 9",
//       price: 2300,
//       mainCamera: 40,
//       secondCamera: 32,
//       storage: 128,
//       ram: 6,
//       diagonal: 6.1,
// 	    battery: "3650",
//       description:
//         "HUAWEI P30 wyznacza granicę możliwości fotograficznych smartfonów. Z nim można znaleźć w sobie artystyczną moc i zobaczyć świat z nowej perspektywy. Zabierając go na wakacje odkryjemy zachwycające ujęcia i zamienimy je w cenne wspomnienia. W tym modelu zmieniona została technika wyczuwania kolorów z RGB na RYB aby zapewnić więcej światła na zdjęciach.",
// 	  },
//     1: {
// 	    title: "Huawei Y5P",
// 	    color: "Blue",
// 	    os: "Android 10",
//       price: 399,
//       mainCamera: 8,
//       secondCamera: 5,
//       storage: 32,
//       ram: 2,
//       diagonal: 5.4,
// 	    battery: "3020",
//       description:
//         "HUAWEI Y5P wyposażony jest w przedni aparat o rozdzielczości 5 Mpix oraz tylny aparat o rozdzielczości 8 Mpix. Na pokładzie smartfona znajduje się procesor Mediatek MT6762R o częstotliwości taktowania 4 × 2.0 GHz + 4 × 1.5 GHz. Pamięć telefonu możemy rozszerzyć nawet do 512 GB za pomocą karty microSD.",
// 	  },
//     2: {
// 	    title: "Huawei P8 Lite",
// 	    color: "Black",
// 	    os: "Android 5.0",
//       price: 730,
//       mainCamera: 13,
//       secondCamera: 5,
//       storage: 16,
//       ram: 2,
//       diagonal: 5,
// 	    battery: "2200",
//       description:
//         "Smartphone firmy Huawei. Procesor Hisilicon Kirin 620, 1.2GHz. Przekątna ekranu 5 cali. Tylny aparat 13 mpx, przedni aparat 5 mpx. Wbudowana pamięć RAM 2 GB, wbudowana pamięć wewnętrzna 16 GB.",
// 	  },
//     3: {
// 	    title: "Huawei Mate 20 Pro",
// 	    color: "Purple",
// 	    os: "Android 9",
//       price: 3090,
//       mainCamera: 40,
//       secondCamera: 24,
//       storage: 128,
//       ram: 6,
//       diagonal: 6.4,
// 	    battery: "4200",
//       description:
//         "Huawei Mate 20 Pro to najpotężniejszy smartfon stworzony przez firmę Huawei. Napędzany potężnym, superwydajnym procesor Kirin 980, wyprodukowanym w litografii 7nm, bezbłędnie obsługuje każdą grę i każdą aplikację. Korzysta przy tym z inteligencji podwójnego chipsetu Neural Processing Unit, ucząc się Twoich zachowań i usprawniając każdy proces. Funkcje AI pomogą Ci również w robieniu zdjęć o profesjonalnej jakości. Ostrych, barwnych, szczegółowych. Pomogą Ci również w robieniu selfie – trójwymiarowego selfie, które czaruje niezwykłą głębią.",
// 	  }
//   },
//   'sony': {
//     0: {
// 	    title: "Sony Xperia X",
// 	    color: "Black",
// 	    os: "Android 6.0",
//       price: 1030,
//       mainCamera: 23,
//       secondCamera: 13,
//       storage: 32,
//       ram: 3,
//       diagonal: 5,
// 	    battery: "2620",
//       description:
//         "Smartfon Xperia X został zaprojektowany, aby idealnie pasował do dłoni, wykonywanych zadań i Twojego stylu. Ulepszony interfejs użytkownika, dzięki czemu jest bardziej intuicyjny niż kiedykolwiek wcześniej. Telefon, który urzeka swoją prostotą.",
// 	  },
//     1: {
// 	    title: "Sony Xperia Z3 Compact",
// 	    color: "Black",
// 	    os: "Android 4.4",
//       price: 800,
//       mainCamera: 20.7,
//       secondCamera: 2.2,
//       storage: 16,
//       ram: 2,
//       diagonal: 4.6,
// 	    battery: "2600",
//       description:
//         "Xperia Z3 Compact to smartfon, który zmieni Twoje życie na lepsze. Wyjdź na zewnątrz, aby czerpać więcej. Dzięki najwyższej klasie wodoodporności smartfon Xperia Z3 Compact umożliwia prowadzenie rozmów w deszczu i robienie zdjęć w basenie. Smartfon jest również odporny na przypadkowe zalanie wodą. Dzięki wyjątkowo cienkiej, zgrabnej konstrukcji, która umożliwia obsługę jedną dłonią, Xperia Z3 Compact z systemem Android oferuje idealne połączenie trwałości i atrakcyjnego wyglądu.",
// 	  },
//     2: {
// 	    title: "Sony Xperia Z2",
// 	    color: "Black",
// 	    os: "Android 4.4",
//       price: 700,
//       mainCamera: 20.7,
//       secondCamera: 2.2,
//       storage: 16,
//       ram: 3,
//       diagonal: 5.2,
// 	    battery: "3200",
//       description:
//         "Telefon Xperia Z2 uwieczni każdą chwilę. Większy przetwornik obrazu. Zdumiewające rezultaty. Dzięki rozdzielczości 20,7 megapikseli i przetwornikowi o 30% większemu niż w standardowych smartfonach telefon Xperia Z2 z Androidem może śmiało konkurować z cyfrowymi kompaktowymi aparatami fotograficznymi. Efektem są niezwykle ostre i wyraźne obrazy.",
// 	  },
//     3: {
// 	    title: "Sony Xperia XA",
// 	    color: "Black",
// 	    os: "Android 6.0",
//       price: 940,
//       mainCamera: 13,
//       secondCamera: 8,
//       storage: 16,
//       ram: 2,
//       diagonal: 5,
// 	    battery: "2300",
//       description:
//         "Smartfon ten łączy w sobie niesamowity wyświetlacz o pełnej szerokości, opływową konstrukcję i idealne wymiary. Jest po prostu idealny. Zakrzywiony wyświetlacz idealnie łączy się z zaokrągloną ramką. Smartfon doskonale wygląda i leży w dłoni.",
// 	  }
//   },
//   'lg': {
//     0: {
// 	    title: "LG V40 ThinQ",
// 	    color: "Grey",
// 	    os: "Android 8.1",
//       price: 1800,
//       mainCamera: 16,
//       secondCamera: 8+5,
//       storage: 128,
//       ram: 6,
//       diagonal: 6.4,
// 	    battery: "3300",
//       description:
//         "Klasyka i nowoczesność przeplata się smukłej obudowie LG V40. Anodowana aluminiowa ramka o zaokrąglonych brzegach, spina ze sobą dwie tafle szkła, tworząc zwartą, odporną na wodę i pył konstrukcję. Front smartfonu zachwyca panoramiczną matrycą OLED z minimalistycznym wcięciem, mieszczącym dwa obiektywy kamery selfie. Z tyłu znalazł się potrójny aparat ze wsparciem AI. Całości dopełnia bezkompromisowa wydajność procesora Snapdragon 845 oraz dźwięk 3D płynący z dwóch głośników, umiejscowionych po obu stronach ekranu.",
// 	  },
//     1: {
// 	    title: "LG K20",
// 	    color: "Blue",
// 	    os: "Android 9",
//       price: 370,
//       mainCamera: 8,
//       secondCamera: 5,
//       storage: 16,
//       ram: 1,
//       diagonal: 5.45,
// 	    battery: "3000",
//       description:
//         "LG K20 to urządzenie o kompaktowych rozmiarach. Świetnie wygląda, jest odporny, ma ergonomiczny kształt, bardzo wygodnie obsługuje się go jedną ręką. Poza ładnym wyglądem, LG K20 oferuje również nieprzeciętną specyfikację, która zapewni płynne działanie i długi czas pracy na jednym ładowaniu. Jest to możliwe dzięki zastosowaniu baterii o pojemności aż 3000 mAh. Całość dopełnia przestronny wyświetlacz FullVision o romiarze 5.45''.",
// 	  },
//     2: {
// 	    title: "LG K40s",
// 	    color: "Blue",
// 	    os: "Android 9",
//       price: 560,
//       mainCamera: 13,
//       secondCamera: 13,
//       storage: 32,
//       ram: 2,
//       diagonal: 6.1,
// 	    battery: "3500",
//       description:
//         "Wyświetlacz o przekątnej 6,1'' z rozdzielczością 1520 × 720 pikseli, system operacyjny Android 9.0, wojskowa odporność MIL-STD-810G, 8-rdzeniowy procesor MediaTek Helio P22, 2 GB/32 GB, dedykowane gniazdo karty pamięci, Dual SIM. Podwójny ekran panoramiczny, aparat 13 + 5 Mpx, aparat selfie 13 Mpx, czytnik linii papilarnych. Bateria o pojemności 3500 mAh, NFC, LTE, dźwięk przestrzenny 3D DTS:X.",
// 	  },
//     3: {
// 	    title: "LG V30",
// 	    color: "Blue",
// 	    os: "Android 6.0",
//       price: 2100,
//       mainCamera: 16,
//       secondCamera: 8,
//       storage: 64,
//       ram: 4,
//       diagonal: 6,
// 	    battery: "3300",
//       description:
//         "Smukła linia, efektowne zakrzywienia i doskonałe proporcje sprawiają, że LG V30 pięknie się prezentuje. Wąskie ramki zapewniają wygodę obsługi i nadają smartfonowi eleganckiego wyglądu. Wykończenie ze szkła i metalu podkreśla prestiżowy charakter smartfonu. LG V30 szczyci się certyfikatem IP68 oraz militarnym standardem odporności MILSTD-810G. Oznacza to, że smartfon może pracować w wilgoci, pyle, a nawet skrajnych temperaturach. Rewolucyjny wyświetlacz LG OLED wyróżnia się doskonałym odwzorowaniem kolorów i szczegółowością obrazu. Dzięki technologii FullVision, 6-calowy ekran LG V30 to prawdziwa gratka dla miłośników seriali i gier.",
// 	  }
//   }
// };

export const brandList = [
  {
    id: 1,
    name: "Samsung",
  },
  {
    id: 2,
    name: "Xiaomi",
  },
  {
    id: 3,
    name: "Nokia",
  },
  {
    id: 4,
    name: "Oppo",
  },
  {
    id: 5,
    name: "OnePlus",
  },
  {
    id: 6,
    name: "Apple",
  },
  {
    id: 7,
    name: "Huawei",
  },
  {
    id: 8,
    name: "LG",
  },
];
